# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.hostname = "opendocker"
  config.vm.network "forwarded_port", guest: 2375, host: 2375
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./playbook.yml"
  end
end
